# Generated by Django 3.1.4 on 2020-12-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='ip')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='last check')),
                ('last_status', models.CharField(blank=True, max_length=64, verbose_name='last status')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='image')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='tag')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
            ],
        ),
    ]
