# Generated by Django 3.1.4 on 2020-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('last_check', models.DateTimeField(null=True, verbose_name='last check')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('image', models.CharField(max_length=100, null=True, verbose_name='image')),
                ('tag', models.CharField(max_length=100, null=True, verbose_name='tag')),
            ],
        ),
    ]
