# Generated by Django 3.1.4 on 2020-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='last status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='tag'),
            preserve_default=False,
        ),
    ]
