# Generated by Django 3.1.4 on 2020-12-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_auto_20201204_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'algo'), (2, 'algo 2')], max_length=255, null=True),
        ),
    ]
