# Generated by Django 3.1.4 on 2020-12-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_dispositivo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='status',
        ),
    ]
