name: build_temperature_reader

# Build only if the temperature_reader folder changes, ignoring documentation
# files like markdown
on:
    push:
        paths:
            - 'app/temperature_reader/**'
            - '!app/temperature_reader/**.md'

jobs:
    build:

        name: Build sensors
        runs-on: ubuntu-latest
        steps:
            -
              name: Checkout
              uses: actions/checkout@v2

            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            -
              name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            -
              name: Login to GitHub Container Registry
              uses: docker/login-action@v1 
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.CR_PAT }}

            -
              name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: app/temperature_reader/
                file: app/temperature_reader/Dockerfile
                platforms: linux/arm/v7,linux/arm64
                push: true
                tags: |
                  ${{ secrets.IMAGE_PATH }}:${{ steps.extract_branch.outputs.branch }}
            
            - name: curl
              continue-on-error: true
              uses: wei/curl@v1
              with:
                args: https://${{ secrets.DASHBOARD_URL }}/dashboard/new_version/${{ steps.extract_branch.outputs.branch }}
